export const tr = {
  navigation: {
    home: "Ana Sayfa",
    live: "Canlı",
    analytics: "Geçmiş Yayınlar",
    community: "Topluluk",
    gallery: "Galeri",
    setup: "Yayın Ekipmanları",
    faq: "Sık Sorulan Sorular",
    admin: "Yönetici Paneli",
  },
  common: {
    loading: "Yükleniyor...",
    error: "Bir hata oluştu",
    success: "Başarılı",
    save: "Kaydet",
    edit: "Düzenle",
    delete: "Sil",
    cancel: "İptal",
    actions: "İşlemler",
    search: "Ara...",
    noData: "Veri Bulunamadı",
    lastUpdated: "Son Güncelleme",
    viewAll: "Tümünü Gör",
    buyNow: "Satın Al",
    outOfStock: "Stokta Yok",
    inStock: "Stokta",
    comingSoon: "Yakında",
    status: "Durum",
    availability: "Stok Durumu",
    notAvailable: "Veri Bulunamadı",
  },
  home: {
    liveTitle: "Canlı Yayın",
    offlineTitle: "Çevrimdışı",
    recentBroadcasts: "Son Yayınlar",
    communitySuggestions: "Oyun Önerileri",
    gearShowcase: "Yayın Ekipmanları",
    viewFullSetup: "Tüm Ekipmanları Gör",
    viewAllBroadcasts: "Tüm Yayınları Gör",
  },
  live: {
    offlineShowcase: "Çevrimdışı Görünüm",
    viewersCount: "İzleyici",
    game: "Oyun/Kategori",
    title: "Yayın Başlığı",
  },
  analytics: {
    title: "Geçmiş Yayınlar",
    date: "Yayın Tarihi",
    broadcastTitle: "Yayın Başlığı",
    category: "Kategori",
    duration: "Yayın Süresi",
    avgViewers: "Ortalama İzleyici",
    peakViewers: "En Yüksek İzleyici",
    totalViews: "Toplam İzlenme",
    status: "Yayın Durumu",
    hours: "Saat",
    minutes: "Dakika",
    seconds: "Saniye",
  },
  community: {
    title: "Topluluk & Oyun Önerileri",
    suggestGame: "Oyun Öner",
    gameCover: "Oyun Kapağı",
    gameName: "Oyun Adı",
    suggestedBy: "Öneren Kullanıcı",
    totalVotes: "Toplam Oy",
    sentDate: "Gönderilme Tarihi",
    topRequestedGames: "En Çok İstenen Oyunlar",
  },
  setup: {
    title: "Yayın Ekipmanları & Donanımları",
    specifications: "Teknik Özellikler",
    brand: "Marka",
    category: "Kategori",
    price: "Fiyat",
    description: "Açıklama",
  },
  admin: {
    title: "Admin Paneli",
    activityLog: "Aktivite Günlüğü",
    setupCrud: "Setup Ürün Yönetimi",
    streamHistory: "Yayın Geçmişi Yönetimi",
    gameSuggestions: "Oyun Önerileri Yönetimi",
    galleryManagement: "Galeri Yönetimi",
    faqCrud: "FAQ (Sık Sorulan Sorular) Yönetimi",
    siteSettings: "Site Ayarları Yönetimi",
  }
};
