$dirs = @(
  "src/components/ui",
  "src/components/common",
  "src/features/live/components",
  "src/features/live/hooks",
  "src/features/live/services",
  "src/features/live/types",
  "src/features/live/validators",
  "src/features/analytics/components",
  "src/features/analytics/hooks",
  "src/features/analytics/services",
  "src/features/analytics/types",
  "src/features/analytics/validators",
  "src/features/community/components",
  "src/features/community/hooks",
  "src/features/community/services",
  "src/features/community/types",
  "src/features/community/validators",
  "src/features/clips/components",
  "src/features/clips/hooks",
  "src/features/clips/services",
  "src/features/clips/types",
  "src/features/clips/validators",
  "src/features/setup/components",
  "src/features/setup/hooks",
  "src/features/setup/services",
  "src/features/setup/types",
  "src/features/setup/validators",
  "src/features/gallery/components",
  "src/features/gallery/hooks",
  "src/features/gallery/services",
  "src/features/gallery/types",
  "src/features/gallery/validators",
  "src/features/timeline/components",
  "src/features/timeline/hooks",
  "src/features/timeline/services",
  "src/features/timeline/types",
  "src/features/timeline/validators",
  "src/features/faq/components",
  "src/features/faq/hooks",
  "src/features/faq/services",
  "src/features/faq/types",
  "src/features/faq/validators",
  "src/features/admin/components",
  "src/features/admin/hooks",
  "src/features/admin/services",
  "src/features/admin/types",
  "src/features/admin/validators",
  "src/services",
  "src/lib/supabase",
  "src/hooks",
  "src/providers",
  "src/types",
  "src/styles",
  "src/config",
  "supabase/functions",
  "supabase/migrations"
)

foreach ($d in $dirs) {
  New-Item -ItemType Directory -Force -Path $d | Out-Null
  New-Item -ItemType File -Force -Path "$d/.gitkeep" | Out-Null
}

Write-Host "All directories created successfully." -ForegroundColor Green
